config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :festivals do
      resources :comments 
  end

  resources :users 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :festival
end

app/models/festival.rb
class Festival < ActiveRecord::Base
	has_many :comments

		has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "1600x1600" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password


	has_many :meetups
	has_many :festivals, through: :meetups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @festival = Festival.find(params[:festival_id])
    @comment = @festival.comments.create(comment_params)
    redirect_to festival_path(@festival)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController

	def index
		@festivals = Festival.all
	end

	def show
		@festivals = Festival.all
		@festival = Festival.find(params[:id])
	end

	def new
		@festival = Festival.new
	end

	def create
		@festival = Festival.new(festival_params)
		if @festival.save
			session[:festival_id] = @festival.id.to_s	
			redirect_to festivals_path
		else
			render :new
		end
	end

	def edit
		@festival = Festival.find(params[:id])
	end

	def update
		@festival = Festival.find(params[:id])
		if @festival.update_attributes(festival_params)
			redirect_to festivals_path
		else 
			render :edit		
		end
	end

	def destroy
		festival = Festival.find(params[:id])
		Comment.where({festival_id: festival.id }).destroy_all
		Festival.destroy
		redirect_to festivals_path
	end

	private

	def festival_params
		params.require(:festival).permit(:name, :date, :location, :info, :image)
	end
end

	

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	 user = User.find_by(email: params[:login][:email])
  	 if user && user.authenticate(params[:login][:password])
  	 	session[:user_id] = user.id.to_s
      	redirect_to users_path
  	 else
  	 	render :new
  	 end	
  end

  def destroy
  	session.delete(:user_id)
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s	
			redirect_to users_path
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path
		else 
			render :edit		
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:name, :age, :country, :email, :password, :password_confirmation, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
  		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/festivals/edit.html.erb
<h1>Edit this Festival</h1>

<%= form_for @festival do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div>
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image%>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

<%= link_to "Back to the list!", festivals_path %>

app/views/festivals/index.html.erb
<h1>Festivals</h1> <br>

<table class="table table-striped table-bordered">
 <thead>
   <tr>
     <th>Name</th>
     <th>Date</th>
     <th>Location</th>
     <th>Info</th>
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @festivals.each do |festival| %>
     <tr>
       <td><%= festival.name %></td>
       <td><%= festival.date %></td>
       <td><%= festival.location %></td>
       <td><%= link_to "More Info", festival_path(festival) %></td> 
     </tr>
   <% end %>
 </tbody>
</table>

<br>

app/views/festivals/new.html.erb
<h1>Add New Festivals</h1>

<%= form_for @festival do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div>
    <%= f.label :locaton %>
    <%= f.text_field :location %>
  </div>

  <div>
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>

  <br><br>
    <%= f.label :image %>
    <%= f.file_field :image%>
  <br><br>

  <div>
    <%= f.submit "Add new Festival!" %>
  </div>

<% end %>

<%= link_to "Back to the list!", festivals_path %>

app/views/festivals/show.html.erb
<h1> <%= @festival.name %> </h1> <br>

<%= image_tag @festival.image.url(:large), :class => "img-responsive"%> <br><br>
<%= @festival.name %>
<%= @festival.date %>
<%= @festival.location %>
<%= @festival.info %>

<br> <br>

<%= link_to "Edit this festival!", edit_festival_path(@festival) %>
<br>

<%= link_to "Delete this festival!", festival_path, method: :delete, data: {confirm: "you sure?"} %>

<br>


<h2>Comments</h2>
<% @festival.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
 

<h3>Add a comment:</h3>
<%= form_for([@festival, @festival.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to "Back to the list!", festivals_path %>

app/views/layouts/_forms.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
 <div class="container-fluid">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="#">Festy</a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav"> 
       <li><%= link_to "Users", users_path %></li>
       <li><%= link_to "Festivals", festivals_path %></li>
       
     </ul>
     <ul class="nav navbar-nav navbar-right">
          <ul class="nav navbar-nav">
             <% if current_user %>
                Logged in as: <%= current_user.name %> <br> <%= link_to 'Log Out', logout_path, method: :delete %>
              <% else %>
                <%= link_to 'Log In', login_path, :class => "navbar-brand" %> 
                <%= link_to 'Sign Up', new_user_path, :class => "navbar-brand" %>
              <% end %>
          </ul>    
         </ul>
       </li>
     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prototype</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container">
<%= yield %>


<%# console %>
<%#= current_user.name if current_user%>
<%#= link_to 'Log Out', logout_path, method: :delete %>



</div>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit this user!</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :age %>
        <%= f.text_field :age %>
    </div>

    <div>
        <%= f.label :country %>
        <%= f.text_field :country %>
    </div>

      <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
     </div>

    <br>

    <%= f.submit "Save these changes!" %>

<% end %>

<br>

<%= link_to "Back to the list!", users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %> <br><br>

    <table class="table table-condensed" > 
    	<strong> <%= user.name %> </strong>
    	<%= link_to "More Info", user_path(user) %>
    	<br><hr>

    </table>
  <% end %>
</ul>

	

app/views/users/new.html.erb
<h1>Log In</h1>

<%= form_for @user, :class => "form-group" do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </div>


  <div class="form-group">
    <%= f.submit "Add new User!", :class => "btn btn-default" %>
  </div>

<% end %>

<%= link_to "Back to the list!", users_path %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<p> <%= @user.name %> is <%= @user.age %> and from <%= @user.country %>! </p>

<%= link_to "Edit this user!", edit_user_path(@user) %>
<br>

<%= link_to "Delete this user!", user_path, method: :delete, data: {confirm: "you sure?"} %>

<br>

<%= link_to "Back to the list!", users_path %>